// <auto-generated />
using ABC._11june_Abhishek.DB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ABC._11june_Abhishek.DB.Migrations
{
    [DbContext(typeof(SongManagementContext))]
    [Migration("20240611091725_fisrt")]
    partial class fisrt
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ABC._11june_Abhishek.Entity.Singer", b =>
                {
                    b.Property<int>("SingerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SingerId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SingerId");

                    b.ToTable("Singer");
                });

            modelBuilder.Entity("ABC._11june_Abhishek.Entity.Songs", b =>
                {
                    b.Property<int>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SongId"), 1L, 1);

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Song")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SongId");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("ABC._11june_Abhishek.Entity.SungBy", b =>
                {
                    b.Property<int>("SungById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SungById"), 1L, 1);

                    b.Property<int>("SingerId")
                        .HasColumnType("int");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.HasKey("SungById");

                    b.HasIndex("SingerId");

                    b.HasIndex("SongId");

                    b.ToTable("SungBy");
                });

            modelBuilder.Entity("ABC._11june_Abhishek.Entity.SungBy", b =>
                {
                    b.HasOne("ABC._11june_Abhishek.Entity.Singer", "Singer")
                        .WithMany("SungBy")
                        .HasForeignKey("SingerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ABC._11june_Abhishek.Entity.Songs", "Songs")
                        .WithMany("SungBy")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Singer");

                    b.Navigation("Songs");
                });

            modelBuilder.Entity("ABC._11june_Abhishek.Entity.Singer", b =>
                {
                    b.Navigation("SungBy");
                });

            modelBuilder.Entity("ABC._11june_Abhishek.Entity.Songs", b =>
                {
                    b.Navigation("SungBy");
                });
#pragma warning restore 612, 618
        }
    }
}
